<?php

namespace App\Http\Controllers;

use App\Models\CalendarEvent;
use App\Models\Holiday;
use App\Helpers\Qs;
use App\Services\GoogleCalendarService;
use App\Services\AcademicCalendarGeneratorService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Log;

class CalendarController extends Controller
{
    protected GoogleCalendarService $gcal;

    public function __construct(GoogleCalendarService $gcal)
    {
        $this->middleware('auth')->except(['icsPublicFeed']);
        $this->gcal = $gcal;
    }

    // ── Index: auto-generate if empty ────────────────────────────────────────

    public function index()
    {
        $icsUrl        = route('calendar.ics');
        $gcalSubscribe = 'https://calendar.google.com/calendar/r?cid=' . urlencode($icsUrl);

        // First-visit bootstrap: generate current academic year automatically
        if (CalendarEvent::count() === 0) {
            try {
                app(AcademicCalendarGeneratorService::class)
                    ->generateAcademicYear((int) date('Y'));
            } catch (\Throwable $e) {
                Log::warning('Auto-generation on first visit failed: ' . $e->getMessage());
            }
        }

        // Academic Year Manager data (for the second tab)
        $years   = \App\Models\AcademicYear::with(['events', 'holidays'])->orderByDesc('start_date')->get();
        $rules   = \App\Models\CalendarRule::orderBy('sort_order')->get();
        $current = \App\Models\AcademicYear::where('is_current', true)->first();

        return view('pages.calendar.index', compact('icsUrl', 'gcalSubscribe', 'years', 'rules', 'current'));
    }

    // ── Events JSON for FullCalendar ──────────────────────────────────────────

    public function events(Request $req)
    {
        $start  = $req->get('start');
        $end    = $req->get('end');
        $yearId = $req->get('year_id'); // optional: browse a specific academic year

        // Resolve which academic year to show
        if ($yearId) {
            $academicYear = \App\Models\AcademicYear::find($yearId);
        } else {
            $academicYear = \App\Models\AcademicYear::where('is_current', true)->first()
                         ?? \App\Models\AcademicYear::where('status', 'active')->latest()->first()
                         ?? \App\Models\AcademicYear::latest()->first();
        }

        $output = [];

        // 1. Calendar events — scoped to the resolved academic year
        $eventsQuery = CalendarEvent::query();

        if ($academicYear) {
            $eventsQuery->where(function ($q) use ($academicYear) {
                $q->where('academic_year_id', $academicYear->id)
                  ->orWhereNull('academic_year_id'); // include manually added events with no year
            });
        }

        $eventsQuery
            ->when($start, fn($q) => $q->where('start_date', '>=', $start))
            ->when($end,   fn($q) => $q->where('start_date', '<=', $end))
            ->get()
            ->each(function ($e) use (&$output) {
                $eth      = CalendarEvent::toEthiopian(new \DateTime($e->start_date->format('Y-m-d')));
                $ethLabel = CalendarEvent::$ethiopianMonths[$eth['month']] . ' ' . $eth['day'] . ', ' . $eth['year'] . ' E.C.';

                $endDate = null;
                if ($e->end_date) {
                    $endDate = \Carbon\Carbon::parse($e->end_date)->addDay()->format('Y-m-d');
                }

                $output[] = [
                    'id'              => 'ev_' . $e->id,
                    'title'           => $e->title,
                    'start'           => $e->start_date->format('Y-m-d') . ($e->start_time ? 'T' . $e->start_time : ''),
                    'end'             => $endDate,
                    'allDay'          => (bool) $e->all_day,
                    'backgroundColor' => $e->color,
                    'borderColor'     => $e->color,
                    'textColor'       => '#ffffff',
                    'extendedProps'   => [
                        'dbId'          => $e->id,
                        'description'   => $e->description,
                        'type'          => $e->type,
                        'ethDate'       => $ethLabel,
                        'notifyEmail'   => (bool) $e->notify_email,
                        'googleEventId' => $e->google_event_id,
                        'addToGcalUrl'  => GoogleCalendarService::addToGoogleUrl($e),
                        'autoGenerated' => (bool) ($e->auto_generated ?? false),
                        'conflictNote'  => $e->conflict_note ?? null,
                    ],
                ];
            });

        // 2. Holidays — scoped to the same academic year
        $holidaysQuery = \App\Models\Holiday::query();
        if ($academicYear) {
            $holidaysQuery->where('academic_year_id', $academicYear->id);
        }

        $holidaysQuery
            ->when($start, fn($q) => $q->where('date', '>=', $start))
            ->when($end,   fn($q) => $q->where('date', '<=', $end))
            ->get()
            ->each(function ($h) use (&$output) {
                $eth      = CalendarEvent::toEthiopian(new \DateTime($h->date->format('Y-m-d')));
                $ethLabel = CalendarEvent::$ethiopianMonths[$eth['month']] . ' ' . $eth['day'] . ', ' . $eth['year'] . ' E.C.';

                $output[] = [
                    'id'              => 'hol_' . $h->id,
                    'title'           => '🇪🇹 ' . $h->name,
                    'start'           => $h->date->format('Y-m-d'),
                    'end'             => null,
                    'allDay'          => true,
                    'backgroundColor' => '#ef4444',
                    'borderColor'     => '#dc2626',
                    'textColor'       => '#ffffff',
                    'extendedProps'   => [
                        'dbId'        => $h->id,
                        'description' => 'Public Holiday',
                        'type'        => 'holiday',
                        'ethDate'     => $ethLabel,
                        'addToGcalUrl'=> 'https://calendar.google.com/calendar/render?action=TEMPLATE'
                            . '&text=' . urlencode($h->name)
                            . '&dates=' . $h->date->format('Ymd') . '/' . $h->date->copy()->addDay()->format('Ymd'),
                    ],
                ];
            });

        return response()->json($output);
    }

    // ── CRUD ──────────────────────────────────────────────────────────────────

    public function store(Request $req)
    {
        $req->validate([
            'title'      => 'required|string|max:200',
            'start_date' => 'required|date',
            'end_date'   => 'nullable|date|after_or_equal:start_date',
            'color'      => 'nullable|string|max:20',
            'type'       => 'nullable|string|max:50',
        ]);

        $event = CalendarEvent::create([
            'title'        => $req->title,
            'description'  => $req->description,
            'start_date'   => $req->start_date,
            'end_date'     => $req->end_date,
            'start_time'   => $req->start_time ?: null,
            'end_time'     => $req->end_time ?: null,
            'color'        => $req->color ?: '#4f46e5',
            'type'         => $req->type ?: 'event',
            'all_day'      => $req->boolean('all_day', true),
            'notify_email' => $req->boolean('notify_email'),
            'notify_roles' => $req->notify_roles ? implode(',', (array) $req->notify_roles) : null,
            'created_by'   => Auth::id(),
        ]);

        $googleId = $this->gcal->pushEvent($event);
        if ($googleId) {
            $event->update(['google_event_id' => $googleId]);
        }

        if ($event->notify_email && $event->notify_roles) {
            $this->sendEventNotifications($event);
        }

        return response()->json([
            'ok'           => true,
            'msg'          => 'Event created.' . ($googleId ? ' Synced to Google Calendar.' : ''),
            'event'        => $event,
            'addToGcalUrl' => GoogleCalendarService::addToGoogleUrl($event),
        ]);
    }

    public function update(Request $req, $rid)
    {
        $eventId = intval($rid) ?: intval($req->segment(3));
        $event = CalendarEvent::find($eventId);
        if (!$event) {
            return response()->json(['ok' => false, 'msg' => 'Event not found.'], 404);
        }

        $req->validate(['title' => 'required|string|max:200', 'start_date' => 'required|date']);

        $event->update([
            'title'        => $req->title,
            'description'  => $req->description,
            'start_date'   => $req->start_date,
            'end_date'     => $req->end_date,
            'start_time'   => $req->start_time ?: null,
            'end_time'     => $req->end_time ?: null,
            'color'        => $req->color ?: $event->color,
            'type'         => $req->type ?: $event->type,
            'all_day'      => $req->boolean('all_day', true),
            'notify_email' => $req->boolean('notify_email'),
            'notify_roles' => $req->notify_roles ? implode(',', (array) $req->notify_roles) : null,
        ]);

        $event->refresh();
        $this->gcal->updateEvent($event);

        return response()->json(['ok' => true, 'msg' => 'Event updated.']);
    }

    public function destroy(Request $req, $rid)
    {
        $eventId = intval($rid) ?: intval($req->segment(3));
        $event = CalendarEvent::find($eventId);
        if (!$event) {
            return response()->json(['ok' => false, 'msg' => 'Event not found.'], 404);
        }
        if ($event->google_event_id) {
            $this->gcal->deleteEvent($event->google_event_id);
        }
        $event->delete();
        return response()->json(['ok' => true, 'msg' => 'Event deleted.']);
    }

    // ── ICS Feed ─────────────────────────────────────────────────────────────

    public function icsPublicFeed()
    {
        $events   = CalendarEvent::orderBy('start_date')->get();
        $holidays = Holiday::orderBy('date')->get();
        $appName  = config('app.name', 'St. Mark SMS');

        $lines = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//' . $appName . '//Academic Calendar//EN',
            'CALSCALE:GREGORIAN',
            'METHOD:PUBLISH',
            'X-WR-CALNAME:' . $appName . ' Academic Calendar',
            'X-WR-TIMEZONE:Africa/Addis_Ababa',
        ];

        foreach ($events as $e) {
            $uid     = 'event-' . $e->id . '@' . parse_url(config('app.url'), PHP_URL_HOST);
            $eth     = CalendarEvent::toEthiopian(new \DateTime($e->start_date->format('Y-m-d')));
            $ethLbl  = CalendarEvent::$ethiopianMonths[$eth['month']] . ' ' . $eth['day'] . ', ' . $eth['year'] . ' E.C.';
            $desc    = ($e->description ? $e->description . '\n\n' : '') . 'Ethiopian Date: ' . $ethLbl;

            if ($e->all_day) {
                $dtStart = 'DTSTART;VALUE=DATE:' . $e->start_date->format('Ymd');
                $dtEnd   = 'DTEND;VALUE=DATE:' . ($e->end_date ?? $e->start_date)->addDay()->format('Ymd');
            } else {
                $tz      = 'Africa/Addis_Ababa';
                $dtStart = 'DTSTART;TZID=' . $tz . ':' . $e->start_date->format('Ymd') . 'T' . str_replace(':', '', substr($e->start_time ?? '00:00:00', 0, 5)) . '00';
                $dtEnd   = 'DTEND;TZID=' . $tz . ':' . ($e->end_date ?? $e->start_date)->format('Ymd') . 'T' . str_replace(':', '', substr($e->end_time ?? $e->start_time ?? '01:00:00', 0, 5)) . '00';
            }

            $lines[] = 'BEGIN:VEVENT';
            $lines[] = 'UID:' . $uid;
            $lines[] = 'DTSTAMP:' . $e->updated_at->format('Ymd\THis\Z');
            $lines[] = $dtStart;
            $lines[] = $dtEnd;
            $lines[] = 'SUMMARY:' . $this->icsEscape($e->title);
            $lines[] = 'DESCRIPTION:' . $this->icsEscape($desc);
            $lines[] = 'CATEGORIES:' . strtoupper($e->type);
            $lines[] = 'STATUS:CONFIRMED';
            $lines[] = 'END:VEVENT';
        }

        foreach ($holidays as $h) {
            $uid = 'holiday-' . $h->id . '@' . parse_url(config('app.url'), PHP_URL_HOST);
            $lines[] = 'BEGIN:VEVENT';
            $lines[] = 'UID:' . $uid;
            $lines[] = 'DTSTAMP:' . $h->updated_at->format('Ymd\THis\Z');
            $lines[] = 'DTSTART;VALUE=DATE:' . $h->date->format('Ymd');
            $lines[] = 'DTEND;VALUE=DATE:' . $h->date->addDay()->format('Ymd');
            $lines[] = 'SUMMARY:' . $this->icsEscape($h->name);
            $lines[] = 'CATEGORIES:HOLIDAY';
            $lines[] = 'STATUS:CONFIRMED';
            $lines[] = 'END:VEVENT';
        }

        $lines[] = 'END:VCALENDAR';

        return response(implode("\r\n", $lines) . "\r\n", 200, [
            'Content-Type'        => 'text/calendar; charset=utf-8',
            'Content-Disposition' => 'inline; filename="academic-calendar.ics"',
            'Cache-Control'       => 'no-cache, must-revalidate',
        ]);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    protected function icsEscape(string $str): string
    {
        $str = str_replace(['\\', ';', ','], ['\\\\', '\;', '\,'], $str);
        $str = str_replace(["\r\n", "\n", "\r"], '\\n', $str);
        return $str;
    }

    protected function sendEventNotifications(CalendarEvent $event)
    {
        $roles    = explode(',', $event->notify_roles);
        $users    = \App\User::whereIn('user_type', $roles)->whereNotNull('email')->get();
        $eth      = CalendarEvent::toEthiopian(new \DateTime($event->start_date->format('Y-m-d')));
        $ethLabel = CalendarEvent::$ethiopianMonths[$eth['month']] . ' ' . $eth['day'] . ', ' . $eth['year'] . ' E.C.';
        $gcalUrl  = GoogleCalendarService::addToGoogleUrl($event);

        foreach ($users as $user) {
            try {
                Mail::send('emails.calendar_event', compact('user', 'event', 'ethLabel', 'gcalUrl'), function ($m) use ($user, $event) {
                    $m->to($user->email, $user->name)
                      ->subject('[' . config('app.name') . '] Calendar Event: ' . $event->title);
                });
            } catch (\Exception $e) {
                Log::warning('Calendar notification failed for user ' . $user->id . ': ' . $e->getMessage());
            }
        }
    }
}
